### ISSUE TITLE
Is it ok to use this t470s on ventura?

### ISSUE THREAD

**Issue by marufkusbianto** [Lochneska/t470s-hackintosh#2]
I use this efi references for this t470s, everything is running well and tried running FCP then got fcp's crash. I mean this ventura is too heavy for this thinkpad gen-7 proccessor? Thank you before

**Comment by Lochneska** [comment]
I used Ventura on the T470s with the 7th gen CPU and it ran generally fine, although I only ran relatively light tasks, so I cant really suggest why FCP would crash the system, but it may indeed be a bit too hard to run. I have upgraded from the T470s since, so I can't really test it for myself anymore unfortunately.
